# This Makefile is self documenting via `make help` and makes use of
# structured comments above each target to determine what to output.
# This is generated by a _very basic_ sed script under the `help`
# target. The basic rules are:
#
#  1. Any line starting with two pound signs will be treated as
#     help documentation e.g. `## hello world`
#  2. A colon can be used to create a column to seperate a target
#     and it's description e.g. `## test: runs the test suite`
#  3. Flags/Arguments can be documented by indenting the target by
#     five spaces e.g. `##     MY_FLAG=<string>: provides flag`

SNYK_VALIDATE=snyk-iac-devsecops-challenge

.PHONY: build
build:
	@docker build -t $(SNYK_VALIDATE) --quiet .

.PHONY: validate
validate: build
	@docker run  $(SNYK_VALIDATE)
