version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  security_scans:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

workflows:
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: ask-content
      - security_scans:
          name: Security Scans
          context:
            - analysis_rules-intelligence
